// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WohnungenApi.Data;

#nullable disable

namespace WohnungenApi.Migrations
{
    [DbContext(typeof(WohnungenContext))]
    [Migration("20260108193811_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmenityWohnung", b =>
                {
                    b.Property<int>("AmenitiesId")
                        .HasColumnType("integer")
                        .HasColumnName("amenitiesid");

                    b.Property<int>("WohnungenId")
                        .HasColumnType("integer")
                        .HasColumnName("wohnungenid");

                    b.HasKey("AmenitiesId", "WohnungenId");

                    b.HasIndex("WohnungenId");

                    b.ToTable("wohnungsamenities", (string)null);
                });

            modelBuilder.Entity("WohnungenApi.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("amenities");
                });

            modelBuilder.Entity("WohnungenApi.Models.Benutzer", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("Anzahle_Wohnungen")
                        .HasColumnType("integer")
                        .HasColumnName("anzahle_wohnungen");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("displayname");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<bool?>("IsAgent")
                        .HasColumnType("boolean")
                        .HasColumnName("isagent");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text")
                        .HasColumnName("taxnumber");

                    b.Property<string>("Vorname")
                        .HasColumnType("text")
                        .HasColumnName("vorname");

                    b.HasKey("Id");

                    b.ToTable("benutzer");
                });

            modelBuilder.Entity("WohnungenApi.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("isread");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sentat");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.ToTable("contactmessages");
                });

            modelBuilder.Entity("WohnungenApi.Models.Favorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int>("WohnungId")
                        .HasColumnType("integer")
                        .HasColumnName("wohnungid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.HasKey("UserId", "WohnungId");

                    b.HasIndex("WohnungId");

                    b.ToTable("favorites");
                });

            modelBuilder.Entity("WohnungenApi.Models.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("text")
                        .HasColumnName("senderemail");

                    b.Property<string>("SenderName")
                        .HasColumnType("text")
                        .HasColumnName("sendername");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int>("WohnungId")
                        .HasColumnType("integer")
                        .HasColumnName("wohnungid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WohnungId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("WohnungenApi.Models.Wohnung", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adresse");

                    b.Property<bool?>("Aufzug")
                        .HasColumnType("boolean")
                        .HasColumnName("aufzug");

                    b.Property<bool?>("Balkon")
                        .HasColumnType("boolean")
                        .HasColumnName("balkon");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("beschreibung");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<int?>("Energieausweis")
                        .HasColumnType("integer")
                        .HasColumnName("energieausweis");

                    b.Property<double?>("Flaeche")
                        .HasColumnType("double precision")
                        .HasColumnName("flaeche");

                    b.Property<DateTime?>("FreiAb")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("freiab");

                    b.Property<int?>("Geschoss")
                        .HasColumnType("integer")
                        .HasColumnName("geschoss");

                    b.Property<string>("Heizung")
                        .HasColumnType("text")
                        .HasColumnName("heizung");

                    b.Property<decimal?>("Kaltmiete")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("kaltmiete");

                    b.Property<decimal?>("Kaufpreis")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("kaufpreis");

                    b.Property<decimal?>("Kaution")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("kaution");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<decimal?>("Nebenkosten")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("nebenkosten");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("ownerid");

                    b.Property<string>("PLZ")
                        .HasColumnType("text")
                        .HasColumnName("plz");

                    b.Property<int?>("Stadt")
                        .HasColumnType("integer")
                        .HasColumnName("stadt");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool?>("Stellplatz")
                        .HasColumnType("boolean")
                        .HasColumnName("stellplatz");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titel");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.Property<decimal?>("Warmmiete")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("warmmiete");

                    b.Property<int?>("Zimmer")
                        .HasColumnType("integer")
                        .HasColumnName("zimmer");

                    b.Property<bool?>("ZumKaufen")
                        .HasColumnType("boolean")
                        .HasColumnName("zumkaufen");

                    b.Property<bool?>("ZumMieten")
                        .HasColumnType("boolean")
                        .HasColumnName("zummieten");

                    b.Property<int?>("Zustand")
                        .HasColumnType("integer")
                        .HasColumnName("zustand");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("wohnungen");
                });

            modelBuilder.Entity("WohnungenApi.Models.WohnungAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmenityId")
                        .HasColumnType("integer")
                        .HasColumnName("amenityid");

                    b.Property<int>("WohnungId")
                        .HasColumnType("integer")
                        .HasColumnName("wohnungid");

                    b.HasKey("Id");

                    b.HasIndex("AmenityId");

                    b.HasIndex("WohnungId");

                    b.ToTable("wohnungamenity");
                });

            modelBuilder.Entity("WohnungenApi.Models.Wohnungsbild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasColumnType("text")
                        .HasColumnName("alttext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("ismain");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortorder");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int>("WohnungId")
                        .HasColumnType("integer")
                        .HasColumnName("wohnungid");

                    b.HasKey("Id");

                    b.HasIndex("WohnungId");

                    b.ToTable("wohnungsbilder");
                });

            modelBuilder.Entity("AmenityWohnung", b =>
                {
                    b.HasOne("WohnungenApi.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WohnungenApi.Models.Wohnung", null)
                        .WithMany()
                        .HasForeignKey("WohnungenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WohnungenApi.Models.Favorite", b =>
                {
                    b.HasOne("WohnungenApi.Models.Benutzer", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WohnungenApi.Models.Wohnung", "Wohnung")
                        .WithMany("Favorites")
                        .HasForeignKey("WohnungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Wohnung");
                });

            modelBuilder.Entity("WohnungenApi.Models.Messages", b =>
                {
                    b.HasOne("WohnungenApi.Models.Benutzer", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WohnungenApi.Models.Wohnung", "Wohnung")
                        .WithMany("Messages")
                        .HasForeignKey("WohnungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Wohnung");
                });

            modelBuilder.Entity("WohnungenApi.Models.Wohnung", b =>
                {
                    b.HasOne("WohnungenApi.Models.Benutzer", "Owner")
                        .WithMany("Wohnungen")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WohnungenApi.Models.WohnungAmenity", b =>
                {
                    b.HasOne("WohnungenApi.Models.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WohnungenApi.Models.Wohnung", "Wohnung")
                        .WithMany("WohnungAmenities")
                        .HasForeignKey("WohnungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Wohnung");
                });

            modelBuilder.Entity("WohnungenApi.Models.Wohnungsbild", b =>
                {
                    b.HasOne("WohnungenApi.Models.Wohnung", "Wohnung")
                        .WithMany("Bilder")
                        .HasForeignKey("WohnungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wohnung");
                });

            modelBuilder.Entity("WohnungenApi.Models.Benutzer", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Messages");

                    b.Navigation("Wohnungen");
                });

            modelBuilder.Entity("WohnungenApi.Models.Wohnung", b =>
                {
                    b.Navigation("Bilder");

                    b.Navigation("Favorites");

                    b.Navigation("Messages");

                    b.Navigation("WohnungAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
