namespace PropertyApi.Application.ShortStay.DTOs;

public sealed record ShortStayListingSummaryDto(
    Guid Id,
    string Title,
    string AccommodationTypeCode,
    string AccommodationTypeNameAr,
    int Capacity,
    int Bedrooms,
    int Bathrooms,
    decimal? FromPricePerNight,
    string? City,
    decimal? Latitude,
    decimal? Longitude,
    bool IsPublished,
    string? MainPhotoUrl,
    double? AverageRating,
    int ReviewCount);

public sealed record ShortStayListingDto(
    Guid Id,
    Guid OwnerId,
    Guid? PropertyId,
    int AccommodationTypeId,
    string AccommodationTypeCode,
    string Title,
    string Description,
    int Capacity,
    int Bedrooms,
    int Bathrooms,
    TimeOnly CheckInTime,
    TimeOnly CheckOutTime,
    bool SelfCheckInEnabled,
    bool InstantBookingEnabled,
    bool RequestBookingEnabled,
    // Latitude/Longitude are the caller-visible, already location-visibility-redacted values —
    // null/rounded when LocationVisibility == Approximate and the caller is not authorized to
    // see the exact point. Never redact only in the frontend.
    decimal? Latitude,
    decimal? Longitude,
    string? City,
    string LocationVisibility,
    string? PoolType,
    string? PoolLocation,
    bool? PoolIsSeasonal,
    bool? PoolIsHeated,
    decimal CleaningFee,
    decimal ExtraGuestFee,
    decimal ExtraBedFee,
    bool AllowsSmoking,
    bool AllowsParties,
    bool AllowsPets,
    TimeOnly? QuietHoursStart,
    TimeOnly? QuietHoursEnd,
    string? CustomRulesText,
    int CancellationFreeCancellationDays,
    bool CancellationDepositRefundable,
    string? CancellationCustomTermsText,
    bool IsPublished,
    DateTime? PublishedAt,
    IReadOnlyList<RoomTypeDto> RoomTypes,
    IReadOnlyList<string> PhotoUrls);
